apiVersion: v1
kind: Service
metadata:
  name: test-app-api-init
  labels:
    app: test-app-api-init
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: test-app-api-init
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-api-init
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app-api-init
  name: test-app-api-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-api-init
  template:
    metadata:
      labels:
        app: test-app-api-init
    spec:
      serviceAccountName: test-app-api-init
      containers:
      - image: {{ TEST_APP_DOCKER_IMAGE }}
        imagePullPolicy: Always
        name: test-app
        env:
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-follower.{{ CONJUR_NAMESPACE_NAME }}.svc.cluster.local/api
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      initContainers:
      - image: cyberark/conjur-kubernetes-authenticator
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: CONJUR_VERSION
            value: {{ CONJUR_VERSION }}
          - name: CONTAINER_MODE
            value: init
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-follower.{{ CONJUR_NAMESPACE_NAME }}.svc.cluster.local/api
          - name: CONJUR_AUTHN_URL
            value: https://conjur-follower.{{ CONJUR_NAMESPACE_NAME }}.svc.cluster.local/api/authn-k8s/{{ AUTHENTICATOR_ID }}
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}
          - name: CONJUR_AUTHN_LOGIN
            value: {{ TEST_APP_NAMESPACE_NAME }}/service_account/test-app-api-init
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
